[2019-03-01 00:03:45,836] INFO Unable to read additional data from server sessionid 0x1000011f5fb0000, likely server has closed socket, closing socket connection and attempting reconnect (org.apache.zookeeper.ClientCnxn)
[2019-03-01 00:03:46,949] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-03-01 00:03:46,952] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-03-01 00:03:47,852] INFO Terminating process due to signal SIGINT (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-03-01 00:03:47,855] INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer)
[2019-03-01 00:03:47,857] INFO [KafkaServer id=0] Starting controlled shutdown (kafka.server.KafkaServer)
[2019-03-01 00:03:48,146] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-03-01 00:03:48,147] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-03-01 00:03:48,252] INFO [ZooKeeperClient] Waiting until connected. (kafka.zookeeper.ZooKeeperClient)
[2019-03-01 00:03:50,011] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-03-01 00:03:50,012] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-03-01 00:03:51,635] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-03-01 00:03:51,635] INFO Terminating process due to signal SIGHUP (org.apache.kafka.common.utils.LoggingSignalHandler)
[2019-03-01 00:03:51,912] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-03-01 00:03:51,912] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-03-01 00:03:52,526] INFO [GroupCoordinator 0]: Member kafka-python-1.4.4-fb86e2c5-9f1c-4de2-8e74-5ffd5831ba8d in group velib-monitor-stations has failed, removing it from the group (kafka.coordinator.group.GroupCoordinator)
[2019-03-01 00:03:52,528] INFO [GroupCoordinator 0]: Preparing to rebalance group velib-monitor-stations in state PreparingRebalance with old generation 1 (__consumer_offsets-17) (reason: removing member kafka-python-1.4.4-fb86e2c5-9f1c-4de2-8e74-5ffd5831ba8d on heartbeat expiration) (kafka.coordinator.group.GroupCoordinator)
[2019-03-01 00:03:52,529] INFO [GroupCoordinator 0]: Group velib-monitor-stations with generation 2 is now empty (__consumer_offsets-17) (kafka.coordinator.group.GroupCoordinator)
[2019-03-01 00:03:53,612] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-03-01 00:03:53,613] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-03-01 00:03:55,561] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-03-01 00:03:55,562] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
[2019-03-01 00:03:57,517] INFO Opening socket connection to server localhost/127.0.0.1:2181. Will not attempt to authenticate using SASL (unknown error) (org.apache.zookeeper.ClientCnxn)
[2019-03-01 00:03:57,518] INFO Socket error occurred: localhost/127.0.0.1:2181: Connection refused (org.apache.zookeeper.ClientCnxn)
